#!/usr/bin/env python
# coding=utf-8
# author=dave.fang@outlook.com
# create=20150520


def output_init(uid):
    file_name = "./reports/ana_" + uid + ".html"
    file_object = open(file_name, 'w')
    start_content = ("\n"
                     "<!DOCTYPE html>\n"
                     "<!-- author: dave.fang@outlook.com -->\n"
                     "<html lang=\"en\">\n"
                     "  <head>\n"
                     "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                     "    <meta charset=\"utf-8\">\n"
                     "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                     "    <title>%s - AnaZhiHu </title>\n"
                     "    <link href=\"./ana_tmp/app.css\" rel=\"stylesheet\">\n"
                     "    <link rel=\"icon\" href=\"https://www.davex.pw/static/favicon.ico\">\n"
                     "    <style>\n"
                     "      [ng\\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {\n"
                     "        display: none !important;\n"
                     "      }\n"
                     "      body {\n"
                     "          font-family: Microsoft YaHei !important;\n"
                     "          background-color: #e8e8e8;\n"
                     "          color: #000000;\n"
                     "      }\n"
                     "      header {\n"
                     "        background: #151515;\n"
                     "        border-top: 0px solid #ffc616;\n"
                     "        border-bottom: 3px solid #ffffff;\n"
                     "      }\n"
                     "      a {\n"
                     "        color: #969696;\n"
                     "      }\n"
                     "      .question-agree a {\n"
                     "        color: #337ab7;\n"
                     "      }\n"
                     "    </style>\n"
                     "    <script type=\"text/javascript\" src=\"ana_tmp/jquery.js\"></script>\n"
                     "    <script type=\"text/javascript\">\n"
                     "    window.onload=function(){\n"
                     "        $(\"#detail\").append(\"   Count: \" + $(\".question-agree\").length);\n"
                     "    }\n"
                     "    </script>\n"
                     "  </head>\n"
                     "  <body class=\"ng-scope\" data-feedly-mini=\"yes\">\n"
                     "    <header>\n"
                     "      <div class=\"container\">\n"
                     "        <div class=\"row\">\n"
                     "          <div class=\"logo\">\n"
                     "            <a href=\"https://www.davex.pw/\" target=\"_blank\">\n"
                     "              <img src=\"./ana_tmp/ana_logo.png\" alt=\"AnaZhiHu Logo\">\n"
                     "            </a>\n"
                     "          </div>\n"
                     "          <h1 class=\"hidden-xs\" style=\"color: #c62011\">>_ Analyse ZhiHu</h1>\n"
                     "          <h4 style=\"color: #B51D0F\"><p id=\"detail\">Target:  %s  </p></h4>\n"
                     "          <h2 class=\"sponsored hidden-xs\" style=\"color: #981C00\">Page Generated by <a href=\"https://www.davex.pw/\" style=\"color: #c62011\">AnaZhiHu</a></h2>\n"
                     "        </div>\n"
                     "        <div class=\"row\">\n"
                     "        </div>\n"
                     "      </div>\n"
                     "    </header>\n"
                     "    <section class=\"\">\n"
                     "      <div class=\"container\">\n"
                     "        <div class=\"row\">\n"
                     "          <div ng-show=\"hasResults\" class=\"col-md-12\">\n"
                     "\n"
                     "              <table class=\"table table-hover search-results\" id=\"table\">\n"
                     "                  <thead>\n"
                     "                      <tr>\n"
                     "                          <th class=\"hidden-xs\">\n"
                     "                              <a ng-click=\"sortResults(&#39;Question&#39;)\">\n"
                     "                                  <center>Question</center>\n"
                     "                              </a>\n"
                     "                          </th>\n"
                     "                      </tr>\n"
                     "                  </thead>\n"
                     "                  <tbody>\n"
                    ) % (uid, uid)
    file_object.write(start_content)
    file_object.close()


def output_finished(uid):
    file_name = "./reports/ana_" + uid + ".html"
    file_object = open(file_name, 'a')
    end_content = ('\n'
                   '                  </tbody>\n'
                   '              </table>\n'
                   '\n'
                   '          </div>\n'
                   '        </div><!-- ./row -->\n'
                   '      </div><!-- ./container -->\n'
                   '    </section>\n'
                   '  </body>\n'
                   '</html>\n'
                   ' '
    )
    file_object.write(end_content)
    file_object.close()
    print '\n[+] Results the save path: %s' % file_name


def output_add(question_uri, question_name, uid):
    file_name = "./reports/ana_" + uid + ".html"
    file_object = open(file_name, 'a')
    mid_content = '''
          <tr>
              <td class="question-agree">
                  <a class="question_link" target="_blank" href="%s">%s</a>
              </td>
          </tr>
    ''' % (question_uri, question_name)
    file_object.write(mid_content)
    file_object.close()
